CREATE DATABASE VOLUNTARIADO
GO


USE VOLUNTARIADO
GO

CREATE TABLE ORGANIZACION(
    CODORG SMALLINT IDENTITY(1,1) NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL,
    TIPO_ORG NVARCHAR(25) NOT NULL,
    CORREO NVARCHAR(50) NOT NULL,
    TELEFONO CHAR(9) NOT NULL,
    SECTOR NVARCHAR(20) NOT NULL,
    AMBITO NVARCHAR(20) NOT NULL,
    DESCRIPCION NVARCHAR(500),

    -- CONSTRAINTS
    CONSTRAINT PK_ORGANIZACION PRIMARY KEY (CODORG),
    CONSTRAINT UQ_ORGANIZACION_CORREO UNIQUE (CORREO),
    CONSTRAINT UQ_ORGANIZACION_TELEFONO UNIQUE (TELEFONO),
    CONSTRAINT CK_ORGANIZACION_TIPO_ORG CHECK(TIPO_ORG IN ('ONG', 'FUNDACION', 'ASOCIACION', 'ENTIDAD P�BLICA', 'OTRA')),
    CONSTRAINT CK_ORGANIZACION_SECTOR CHECK(SECTOR IN ('SOCIAL', 'SALUD', 'EDUCATIVO', 'AMBIENTAL', 'CULTURAL', 'DEPORTIVO', 'TECNOL�GICO', 'OTRO')),
    CONSTRAINT CK_ORGANIZACION_AMBITO CHECK(AMBITO IN ('LOCAL', 'REGIONAL', 'NACIONAL', 'INTERNACIONAL')),
    CONSTRAINT CK_ORGANIZACION_TELEFONO CHECK(TELEFONO LIKE '[6-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    CONSTRAINT CK_ORGANIZACION_CORREO CHECK(CORREO LIKE '%@%.%')
)
GO

CREATE INDEX IX_ORGANIZACION_NOMBRE ON ORGANIZACION(NOMBRE)
GO


CREATE TABLE ACTIVIDAD(
    CODACT SMALLINT IDENTITY(1,1) NOT NULL,
    NOMBRE NVARCHAR(70) NOT NULL,
    DURACION_SESION TIME NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    N_MAX_VOLUNTARIOS SMALLINT NOT NULL,
    CODORG SMALLINT NOT NULL,
    DESCRIPCION NVARCHAR(500) NOT NULL,

    -- CONSTRAINTS
    CONSTRAINT PK_ACTIVIDAD PRIMARY KEY (CODACT),
    CONSTRAINT FK_ACTIVIDAD_ORGANIZACION FOREIGN KEY (CODORG) REFERENCES ORGANIZACION(CODORG),
    CONSTRAINT CK_ACTIVIDAD_FECHAS CHECK(FECHA_FIN >= FECHA_INICIO),
    CONSTRAINT CK_ACTIVIDAD_MAX_VOLUNTARIOS CHECK(N_MAX_VOLUNTARIOS > 0)
)
GO
CREATE UNIQUE INDEX IX_ACTIVIDAD_NOMBRE ON ACTIVIDAD(NOMBRE)
CREATE INDEX IX_ACTIVIDAD_CODORG ON ACTIVIDAD(CODORG)

GO


CREATE TABLE ODS(
    NUMODS SMALLINT NOT NULL,
    DESCRIPCION NVARCHAR(70) NOT NULL,
    CONSTRAINT PK_ODS PRIMARY KEY (NUMODS)
)
GO


CREATE TABLE TIPO_ACTIVIDAD(
    CODTIPO SMALLINT IDENTITY(1,1) NOT NULL,
    DESCRIPCION NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_TIPO_ACTIVIDAD PRIMARY KEY (CODTIPO)

	
)
GO

CREATE UNIQUE INDEX IX_TIPO_ACTIVIDAD_DESCRIPCION ON TIPO_ACTIVIDAD(DESCRIPCION)

CREATE TABLE CICLO(
    CODCICLO NVARCHAR(10) NOT NULL,
    NOMBRE NVARCHAR(70) NOT NULL,
    CURSO SMALLINT NOT NULL,

    -- CONSTRAINTS
    CONSTRAINT PK_CICLO PRIMARY KEY (CODCICLO),
    CONSTRAINT CK_CICLO_CURSO CHECK(CURSO > 0)
)
GO

CREATE INDEX IX_CICLO_NOMBRE_CURSO ON CICLO(NOMBRE, CURSO)
GO


CREATE TABLE VOLUNTARIO(
    CODVOL SMALLINT IDENTITY(1,1) NOT NULL,
    NOMBRE NVARCHAR(30) NOT NULL,
    APELLIDO1 NVARCHAR(30) NOT NULL,
    APELLIDO2 NVARCHAR(30),
    CORREO NVARCHAR(50) NOT NULL,
    TELEFONO CHAR(9) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    DESCRIPCION NVARCHAR(500),
    CODCICLO NVARCHAR(10) NOT NULL,

    -- CONSTRAINT
    CONSTRAINT PK_VOLUNTARIO PRIMARY KEY (CODVOL),
    CONSTRAINT UQ_VOLUNTARIO_CORREO UNIQUE (CORREO),
    CONSTRAINT FK_VOLUNTARIO_CICLO FOREIGN KEY (CODCICLO) REFERENCES CICLO(CODCICLO),
    CONSTRAINT CK_VOLUNTARIO_FECHA_NACIMIENTO CHECK(FECHA_NACIMIENTO <= GETDATE()),
    CONSTRAINT CK_VOLUNTARIO_TELEFONO CHECK(TELEFONO LIKE '[6-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    CONSTRAINT CK_VOLUNTARIO_CORREO CHECK(CORREO LIKE '%@%.%')
)
GO

CREATE INDEX IX_VOLUNTARIO_CICLO_NOMBRE ON VOLUNTARIO(CODCICLO, NOMBRE, APELLIDO1, APELLIDO2)
GO


CREATE TABLE DISPONIBILIDAD(
    CODVOL SMALLINT NOT NULL,
    DIA NVARCHAR(10) NOT NULL,
    HORA_SLOT NVARCHAR(10) NOT NULL,

    -- CONSTRAINTS
    CONSTRAINT PK_DISPONIBILIDAD PRIMARY KEY (CODVOL, DIA, HORA_SLOT),
    CONSTRAINT FK_DISPONIBILIDAD_VOLUNTARIO FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO(CODVOL),
    CONSTRAINT CK_DISPONIBILIDAD_DIA CHECK(DIA IN ('LUNES','MARTES','MI�RCOLES','JUEVES','VIERNES','S�BADO','DOMINGO')),
    CONSTRAINT CK_DISPONIBILIDAD_HORA_SLOT CHECK(HORA_SLOT IN ('3-4', '4-5', '5-6', '6-7', '7-8', '8-9', '9-10'))
)
GO


CREATE TABLE ACT_ASOCIADO_TACT(
    CODACT SMALLINT NOT NULL,
    CODTIPO SMALLINT NOT NULL,

    -- CONSTRAINTS
    CONSTRAINT PK_ACT_ASOCIADO_TACT PRIMARY KEY (CODACT, CODTIPO),
    CONSTRAINT FK_ACT_ASOCIADO_TACT_ACTIVIDAD FOREIGN KEY (CODACT) REFERENCES ACTIVIDAD(CODACT),
    CONSTRAINT FK_ACT_ASOCIADO_TACT_TIPO FOREIGN KEY (CODTIPO) REFERENCES TIPO_ACTIVIDAD(CODTIPO)
)
GO


CREATE TABLE VOL_PARTICIPA_ACT(
    CODVOL SMALLINT NOT NULL,
    CODACT SMALLINT NOT NULL,

    -- CONSTRAINTS
    CONSTRAINT PK_VOL_PARTICIPA_ACT PRIMARY KEY (CODVOL, CODACT),
    CONSTRAINT FK_VOL_PARTICIPA_ACT_VOLUNTARIO FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO(CODVOL),
    CONSTRAINT FK_VOL_PARTICIPA_ACT_ACTIVIDAD FOREIGN KEY (CODACT) REFERENCES ACTIVIDAD(CODACT)
)
GO


CREATE TABLE VOL_PREFIERE_TACT(
    CODVOL SMALLINT NOT NULL,
    CODTIPO SMALLINT NOT NULL,

    -- CONSTRAINTS
    CONSTRAINT PK_VOL_PREFIERE_TACT PRIMARY KEY (CODVOL, CODTIPO),
    CONSTRAINT FK_VOL_PREFIERE_TACT_VOLUNTARIO FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO(CODVOL),
    CONSTRAINT FK_VOL_PREFIERE_TACT_TIPO FOREIGN KEY (CODTIPO) REFERENCES TIPO_ACTIVIDAD(CODTIPO)
)
GO


CREATE TABLE ACT_PRACTICA_ODS(
    CODACT SMALLINT NOT NULL,
    NUMODS SMALLINT NOT NULL,

    CONSTRAINT PK_ACT_PRACTICA_ODS PRIMARY KEY (CODACT, NUMODS),
    CONSTRAINT FK_ACT_PRACTICA_ODS_ACTIVIDAD FOREIGN KEY (CODACT) REFERENCES ACTIVIDAD(CODACT),
    CONSTRAINT FK_ACT_PRACTICA_ODS_ODS FOREIGN KEY (NUMODS) REFERENCES ODS(NUMODS)
)

--INSERTARD DATOS EN TABLA ORGANIZACION
INSERT INTO ORGANIZACION (NOMBRE, TIPO_ORG, CORREO, TELEFONO, SECTOR, AMBITO, DESCRIPCION)
VALUES
('AMAVIR', 'FUNDACION', 'amavir@example.com', '600000001', 'SALUD', 'LOCAL', 'Organizaci�n dedicada a la salud de los mayores.'),
('ANA', 'ONG', 'ana@example.com', '600000002', 'SOCIAL', 'REGIONAL', 'ONG enfocada en la ayuda social.'),
('CUATROVIENTOS', 'ASOCIACION', 'cuatrocientos@example.com', '600000003', 'EDUCATIVO', 'NACIONAL', 'Asociaci�n educativa.'),
('SOLERA', 'ENTIDAD P�BLICA', 'solera@example.com', '600000004', 'AMBIENTAL', 'INTERNACIONAL', 'Entidad p�blica ambiental.'),
('UNZUTXIKI', 'OTRA', 'unzutxiki@example.com', '600000005', 'CULTURAL', 'LOCAL', 'Organizaci�n cultural local.');

--INSERTARD DATOS EN TABLA CICLO
INSERT INTO CICLO (CODCICLO, NOMBRE, CURSO)
VALUES
('1SC', 'SERVICIOS COMERCIALES', 1),
('2SC', 'SERVICIOS COMERCIALES', 2),
('1AAG', 'AUXILIAR ADMINISTRATIVO GENERAL', 1),
('2AAG', 'AUXILIAR ADMINISTRATIVO GENERAL', 2),
('1GA', 'GESTI�N ADMINISTRATIVA', 1),
('2GA', 'GESTI�N ADMINISTRATIVA', 2),
('1AC', 'ACTIVIDADES COMERCIALES', 1),
('2AC', 'ACTIVIDADES COMERCIALES', 2),
('1SMR', 'SISTEMAS MICROINFORM�TICOS Y REDES', 1),
('2SMR', 'SISTEMAS MICROINFORM�TICOS Y REDES', 2),
('1AF', 'ADMINISTRACI�N Y FINANZAS', 1),
('2AF', 'ADMINISTRACI�N Y FINANZAS', 2),
('1CI', 'COMERCIO INTERNACIONAL', 1),
('2CI', 'COMERCIO INTERNACIONAL', 2),
('1GV', 'GESTI�N DE VENTAS', 1),
('2GV', 'GESTI�N DE VENTAS', 2),
('1TL', 'TRANSPORTE Y LOG�STICA', 1),
('2TL', 'TRANSPORTE Y LOG�STICA', 2),
('1ASIR', 'ADMINISTRACI�N DE SISTEMAS INFORM�TICOS Y REDES', 1),
('2ASIR', 'ADMINISTRACI�N DE SISTEMAS INFORM�TICOS Y REDES', 2),
('1DAM', 'DESARROLLO DE APLICACIONES MULTIPLATAFORMA', 1),
('2DAM', 'DESARROLLO DE APLICACIONES MULTIPLATAFORMA', 2);

--INSERTARD DATOS EN TABLA VOLUNTARIO
INSERT INTO VOLUNTARIO (NOMBRE, APELLIDO1, APELLIDO2, CORREO, TELEFONO, FECHA_NACIMIENTO, DESCRIPCION, CODCICLO)
VALUES
('Juan', 'P�rez', 'Garc�a', 'juan.perez@example.com', '600000006', '1995-05-20', 'Voluntario entusiasta.', '1SMR'),
('Mar�a', 'L�pez', 'S�nchez', 'maria.lopez@example.com', '600000007', '1998-07-15', 'Interesada en actividades sociales.', '2DAM'),
('Carlos', 'G�mez', 'Mart�nez', 'carlos.gomez@example.com', '600000008', '1990-03-10', NULL, '1DAM'),
('Ana', 'Fern�ndez', 'Ruiz', 'ana.fernandez@example.com', '600000009', '2000-01-01', 'Estudiante de marketing.', '1DAM'),
('Luis', 'Mart�n', 'Hern�ndez', 'luis.martin@example.com', '600000010', '1992-11-25', 'Experiencia en educaci�n.', '2SMR');

--INSERTARD DATOS EN TABLA TIPO_ACTIVIDAD
INSERT INTO TIPO_ACTIVIDAD (DESCRIPCION)
VALUES
('Digital'),
('Salud'),
('Educativo'),
('Ambiental'),
('Deportivo'),
('Social'),
('Cultural'),
('Tecnico');


--INSERTARD DATOS EN TABLA ODS
INSERT INTO ODS (NUMODS, DESCRIPCION)  
VALUES  
(1, 'Fin de la pobreza'),  
(2, 'Hambre cero'),  
(3, 'Salud y bienestar'),  
(4, 'Educaci�n de calidad'),  
(5, 'Igualdad de g�nero'),  
(6, 'Agua limpia y saneamiento'),  
(7, 'Energ�a asequible y no contaminante'),  
(8, 'Trabajo decente y crecimiento econ�mico'),  
(9, 'Industria, innovaci�n e infraestructura'),  
(10, 'Reducci�n de las desigualdades'),  
(11, 'Ciudades y comunidades sostenibles'),  
(12, 'Producci�n y consumo responsables'),  
(13, 'Acci�n por el clima'),  
(14, 'Vida submarina'),  
(15, 'Vida de ecosistemas terrestres'),  
(16, 'Paz, justicia e instituciones s�lidas'),  
(17, 'Alianzas para lograr los objetivos');  

--INSERTARD DATOS EN TABLA ACTIVIDAD
INSERT INTO ACTIVIDAD (NOMBRE, DURACION_SESION, FECHA_INICIO, FECHA_FIN, N_MAX_VOLUNTARIOS, CODORG, DESCRIPCION)
VALUES
('ACTIVIDAD1', '02:00:00', '2023-10-01', '2023-10-02', 10, 1, 'Taller de salud para mayores'),
('ACTIVIDAD2','01:30:00', '2023-11-15', '2023-11-15', 5, 2, 'Reparto de alimentos'),
('ACTIVIDAD3','03:00:00', '2023-12-01', '2023-12-03', 20, 3, 'Jornada educativa'),
('ACTIVIDAD4','01:00:00', '2024-01-10', '2024-01-10', 15, 4, 'Limpieza de playa'),
('ACTIVIDAD5','02:30:00', '2024-02-20', '2024-02-21', 8, 5, 'Festival cultural');


--INSERTARD DATOS EN TABLA DISPONIBILIDAD
INSERT INTO DISPONIBILIDAD (CODVOL, DIA, HORA_SLOT)
VALUES
(1, 'LUNES', '3-4'),
(1, 'MI�RCOLES', '5-6'),
(2, 'MARTES', '4-5'),
(2, 'JUEVES', '6-7'),
(3, 'VIERNES', '7-8'),
(4, 'S�BADO', '8-9'),
(5, 'DOMINGO', '9-10');

--INSERTARD DATOS EN TABLA VOL_PARTICIPA_ACT
INSERT INTO VOL_PARTICIPA_ACT (CODVOL, CODACT)
VALUES
(1, 1),  -- Juan participa en Taller de salud
(2, 2),  -- Mar�a participa en Reparto de alimentos
(3, 3),  -- Carlos participa en Jornada educativa
(4, 4),  -- Ana participa en Limpieza de playa
(5, 5);  -- Luis participa en Festival cultural

--INSERTARD DATOS EN TABLA VOL_PREFIERE_TACT
INSERT INTO VOL_PREFIERE_TACT (CODVOL, CODTIPO)
VALUES
(1, 1),  -- Juan prefiere Educativa
(2, 2),  -- Mar�a prefiere Social
(3, 3),  -- Carlos prefiere Ambiental
(4, 4),  -- Ana prefiere Cultural
(5, 5);  -- Luis prefiere Deportiva


--INSERTARD DATOS EN TABLA ACT_PRACTICA_ODS
INSERT INTO ACT_PRACTICA_ODS (CODACT, NUMODS)
VALUES
(1, 3),  -- Taller de salud (Salud y bienestar)
(2, 2),  -- Reparto de alimentos (Hambre cero)
(3, 4),  -- Jornada educativa (Educaci�n de calidad)
(4, 1),  -- Limpieza de playa (Fin de la pobreza)
(5, 5);  -- Festival cultural (Igualdad de g�nero)

--INSERTARD DATOS EN TABLA ACT_ASOCIADO_TACT
INSERT INTO ACT_ASOCIADO_TACT (CODACT, CODTIPO)
VALUES
(1, 1),  -- Taller de salud (Educativa)
(2, 2),  -- Reparto de alimentos (Social)
(3, 1),  -- Jornada educativa (Educativa)
(4, 3),  -- Limpieza de playa (Ambiental)
(5, 4);  -- Festival cultural (Cultural)



-- PROCESOS ALMACENADOS
--BUSCAR ACTIVIDADES POR UN ODS DADO
GO
CREATE OR ALTER PROCEDURE ActividadesPorODS
    @NumODS SMALLINT
AS
BEGIN
    SELECT A.*
    FROM ACTIVIDAD AS A INNER JOIN ACT_PRACTICA_ODS APO 
                                ON A.CODACT = APO.CODACT
                                    INNER JOIN ODS AS O 
                                            ON O.NUMODS = APO.NUMODS
    WHERE O.NUMODS = @NumODS;
END
GO
EXEC ActividadesPorODS @NumODS = 4;

--BUSCAR ACTIVIDADES REALIZADAS POR UNA ORGANIZACION DADA
GO
CREATE PROCEDURE ObtenerActividadesPorOrganizacion
    @NombreOrganizacion NVARCHAR(50)
AS
    SELECT A.*
    FROM ACTIVIDAD A
    INNER JOIN ORGANIZACION O ON A.CODORG = O.CODORG
    WHERE O.NOMBRE = @NombreOrganizacion
GO
EXEC ObtenerActividadesPorOrganizacion 'ANA';
GO

--BUSCAR VOLUNTARIOS PERTENECIENTES DEL CICLO DADO
CREATE PROCEDURE ObtenerVoluntariosPorCiclo
    @CodigoCiclo NVARCHAR(10)
AS
    SELECT V.*
    FROM VOLUNTARIO V
    INNER JOIN CICLO C ON V.CODCICLO = C.CODCICLO
    WHERE C.CODCICLO = @CodigoCiclo;
GO

EXEC ObtenerVoluntariosPorCiclo '2DAM';




--BUSCAR VOLUNTARIOS DISPONIBLES PARA UNA FECHA DADA
GO
CREATE PROCEDURE ObtenerVoluntariosPorFecha
    @FechaInicio DATE
AS
    DECLARE @DiaSemana NVARCHAR(15)
    DECLARE @NombreDia NVARCHAR(15)

    SET @NombreDia = DATENAME(WEEKDAY, @FechaInicio);

    IF @NombreDia = 'Monday'
        SET @DiaSemana = 'Lunes'
    ELSE IF @NombreDia = 'Tuesday'
        SET @DiaSemana = 'Martes'
    ELSE IF @NombreDia = 'Wednesday'
        SET @DiaSemana = 'Miércoles'
    ELSE IF @NombreDia = 'Thursday'
        SET @DiaSemana = 'Jueves'
    ELSE IF @NombreDia = 'Friday'
        SET @DiaSemana = 'Viernes'
    ELSE IF @NombreDia = 'Saturday'
        SET @DiaSemana = 'Sábado'
    ELSE IF @NombreDia = 'Sunday'
        SET @DiaSemana = 'Domingo'
    ELSE
        SET @DiaSemana = @NombreDia
    SELECT @NombreDia, V.*
    FROM VOLUNTARIO V
    INNER JOIN DISPONIBILIDAD D ON V.CODVOL = D.CODVOL
    WHERE D.DIA = @DiaSemana
GO


EXEC ObtenerVoluntariosPorFecha '2025-04-20';
